server:
  port: 8081
  tomcat:
    uri-encoding: utf-8


spring:
  application:
    name: Tourist-user-server


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true